name: WebdriverIO tests of webtrader.roboforex.com

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Webdriver tests
    steps:
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - name: Run test
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: npm cit ## npm install && npm test together
    - name: Create allure test results artifact
      if: always() ## start even previous steps is failure
      uses: actions/upload-artifact@v2
      with:
        name: allure test report
        path: allure-results
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Generate allure report with history
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report-1
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      id: allure-report-2
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history